---
apiVersion: v1
kind: Namespace
metadata:
  name: dev-ns-app
  labels:
    app: dev-app
    env: dev
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-app-qouta
  namespace: dev-ns-app
spec:
  hard:
    limits.cpu: "10"
    limits.memory: "24Gi"
