---
apiVersion: v1
kind: Namespace
metadata:
  name: dev-ns-app
  labels:
    app: dev-app
    env: dev
spec:
  hard:
    limits.cpu: "10"
    limits.memory: "24Gi"
  resources:
    requests:
      cpu: "6"
      memory: "16Gi"
    limits:
      cpu: "10"
      memory: "24Gi"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: dev-app-limit-range
  namespace: dev-ns-app
spec:
  limits:
  - type: Pod
    min:
      cpu: "500m"
      memory: "256Mi"
    max:
      cpu: "8"
      memory: "20Gi"
  - type: Container
    min:
      cpu: "100m"
      memory: "128Mi"
    max:
      cpu: "8"
      memory: "20Gi"
    default:
      cpu: "4"
      memory: "8Gi"
    defaultRequest:
      cpu: "500m"
      memory: "256Mi"
