---
apiVersion: v1
kind: Namespace
metadata:
  name: dev-lo-wpk
  labels:
    app: lo-wpk
    env: dev
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-wpk-qouta
  namespace: dev-lo-wpk
spec:
  hard:
    limits.cpu: "10"
    limits.memory: "24Gi"
